# Generated by Django 2.0.3 on 2018-03-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
